name: My First Push
on: 
  pull_request:

jobs:
  Tarea1:
    runs-on: ubuntu-22.04
    steps:
      - name: Datos del Push
        run: |
          echo "Rama origen: ${{github.head_ref}}"
          echo "Repositorio origen: ${{github.event.pull_request.head.repo.full_name}}"
          echo "Rama destino: ${{github.base_ref}}"
          echo "Repositorio destino: ${{github.event.pull_request.base.repo.full_name}}"
          echo "Título: ${{github.event.pull_request.title}}"
          echo "Contenido/Descripción: ${{github.event.pull_request.body}}"
          echo "Estado: ${{github.event.pull_request.state}}"
          echo "¿Fue fusionado?: ${{github.event.pull_request.merged}}"
